# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7626f3606474cf7c528153aa5ce972474bfe7b28956da84414f3d86ef2a69e651b4c698038ae3b7b7a19d9e657d38b52240a05ca6f7bc7fad88acad8124ee0da

test:
  secret_key_base: daf5119537a82d3ed21660331e048022ac17dc45e9f2c96683ac56a09078f8f98ea910f4fa5b656b1bd06dcc9b3ce91ec38121aafe7a96d1a736755e87bf5bdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
